language: generic
dist: xenial

install:
  - sudo apt-get -y install netcat-traditional
  - sudo update-alternatives --set nc /bin/nc.traditional
  - sudo pip install tox-travis
#env: DEBUG=true
script: sudo make test-all
